<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lex</string>
		<string>marvell</string>
	</array>
	<key>name</key>
	<string>Lex</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>color templates</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.white)((\s+)|$)</string>
			<key>name</key>
			<string>markup.lex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.white\.italic)((\s+)|$)</string>
			<key>name</key>
			<string>markup.italic.lex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.white\.bold)((\s+)|$)</string>
			<key>name</key>
			<string>markup.bold.lex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(color\.white\.highlight)</string>
			<key>name</key>
			<string>markup.raw.lex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.grey)((\s+)|$)</string>
			<key>name</key>
			<string>comment.lex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.red)((\s+)|$)</string>
			<key>name</key>
			<string>keyword.lex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(color\.red\.highlight)</string>
			<key>name</key>
			<string>invalid.illegal.lex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.orange\.italic)((\s+)|$)</string>
			<key>name</key>
			<string>variable.parameter.lex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.yellow)((\s+)|$)</string>
			<key>name</key>
			<string>string.lex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.green)((\s+)|$)</string>
			<key>name</key>
			<string>entity.name.lex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.green\.italic)((\s+)|$)</string>
			<key>name</key>
			<string>entity.other.inherited-class.lex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.blue)((\s+)|$)</string>
			<key>name</key>
			<string>support.function.lex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.blue\.italic)((\s+)|$)</string>
			<key>name</key>
			<string>storage.type.lex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.purple)((\s+)|$)</string>
			<key>name</key>
			<string>constant.numeric.lex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(color\.purple\.highlight)</string>
			<key>name</key>
			<string>invalid.deprecated.lex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*+)\[(\^?\])?</string>
			<key>comment</key>
			<string>Match headlines in [..]</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>constant.numeric.lex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>comment</key>
			<string>Match block comments /*...*/</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.block.lex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|(\s+))(\-\-|\/\/|\#)</string>
			<key>comment</key>
			<string>Match line comments --, //,</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.lex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|(\s+))\'</string>
			<key>comment</key>
			<string>Match quoted text in '..'</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.lex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|(\s+))\"</string>
			<key>comment</key>
			<string>Match quoted text in ".."</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.lex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>((http://)|(https://)|(ftp://))</string>
			<key>comment</key>
			<string>Match links http:// https://</string>
			<key>end</key>
			<string>((\s+)|$)</string>
			<key>name</key>
			<string>support.type.lex</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match menu items [..]</string>
			<key>match</key>
			<string>^(\s*+)([0-9A-F]\))</string>
			<key>name</key>
			<string>constant.numeric.lex</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match keywords</string>
			<key>match</key>
			<string>(^|(\s+))(lex)((\s+)|$)</string>
			<key>name</key>
			<string>variable.parameter.lex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\&lt;</string>
			<key>comment</key>
			<string>Match block comments &lt;...&gt;</string>
			<key>end</key>
			<string>\&gt;</string>
			<key>name</key>
			<string>entity.name.function.lex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.lex</string>
	<key>uuid</key>
	<string>0f1542b9-eac7-485c-ade4-2f952adb4de5</string>
</dict>
</plist>
