<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>marvell</string>
		<string>tgf.txt</string>
	</array>
	<key>name</key>
	<string>Marvell</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>color templates</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.white)((\s+)|$)</string>
			<key>name</key>
			<string>markup.marvell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.white\.italic)((\s+)|$)</string>
			<key>name</key>
			<string>markup.italic.marvell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.white\.bold)((\s+)|$)</string>
			<key>name</key>
			<string>markup.bold.marvell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(color\.white\.highlight)</string>
			<key>name</key>
			<string>markup.raw.marvell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.grey)((\s+)|$)</string>
			<key>name</key>
			<string>comment.marvell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.red)((\s+)|$)</string>
			<key>name</key>
			<string>keyword.marvell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(color\.red\.highlight)</string>
			<key>name</key>
			<string>invalid.illegal.marvell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.orange\.italic)((\s+)|$)</string>
			<key>name</key>
			<string>variable.parameter.marvell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.yellow)((\s+)|$)</string>
			<key>name</key>
			<string>string.marvell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.green)((\s+)|$)</string>
			<key>name</key>
			<string>entity.name.marvell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.green\.italic)((\s+)|$)</string>
			<key>name</key>
			<string>entity.other.inherited-class.marvell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.blue)((\s+)|$)</string>
			<key>name</key>
			<string>support.function.marvell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.blue\.italic)((\s+)|$)</string>
			<key>name</key>
			<string>storage.type.marvell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|(\s+))(color\.purple)((\s+)|$)</string>
			<key>name</key>
			<string>constant.numeric.marvell</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(color\.purple\.highlight)</string>
			<key>name</key>
			<string>invalid.deprecated.marvell</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match func... and file...</string>
			<key>match</key>
			<string>(?&lt;=\])((\s+)egress port(\s+))(?=(\[))</string>
			<key>name</key>
			<string>support.function.marvell</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match keywords</string>
			<key>match</key>
			<string>\b(slan0.)\b</string>
			<key>name</key>
			<string>markup.bold.marvell</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match func... and file...</string>
			<key>match</key>
			<string>(?&lt;=([\r\n]^.{30}\]))((\s+)ingress port(\s+))(?=(\[))</string>
			<key>name</key>
			<string>support.function.marvell</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|(\s+))(\#\#\#|\^\^\^|\-\-\-|\*\*\*)</string>
			<key>comment</key>
			<string>Match line comments</string>
			<key>end</key>
			<string>(?=($|(SIM_LOG_IN_PACKET_STR)|(SIM_LOG_OUT_REPLICATION_STR)|(SIM_LOG_ENDED_IN_PACKET_STR)))</string>
			<key>name</key>
			<string>comment.marvell</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match square brackets</string>
			<key>match</key>
			<string>(\[|\])</string>
			<key>name</key>
			<string>comment.marvell</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\[)(\b(\s?)(0x?[0-9A-Fa-f]+)(\s?)\b)</string>
			<key>comment</key>
			<string>Match numbers</string>
			<key>end</key>
			<string>(?=(\]))</string>
			<key>name</key>
			<string>constant.numeric.marvell</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\[)(\b(\s?)([0-9]+)(\s?)\b)</string>
			<key>comment</key>
			<string>Match numbers</string>
			<key>end</key>
			<string>(?=(\]))</string>
			<key>name</key>
			<string>constant.numeric.marvell</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match numbers</string>
			<key>match</key>
			<string>((\s?)\b(0x?[0-9A-Fa-f]+)\b(\s?))</string>
			<key>name</key>
			<string>constant.numeric.marvell</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match numbers</string>
			<key>match</key>
			<string>\b[0-9a-f]+\b</string>
			<key>name</key>
			<string>constant.numeric.marvell</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;= func\[)|(?&lt;= file\[)</string>
			<key>comment</key>
			<string>Match func... and file...</string>
			<key>end</key>
			<string>(?=(\]))</string>
			<key>name</key>
			<string>string.marvell</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match keywords</string>
			<key>match</key>
			<string>(SIM_LOG_IN_PACKET_STR|SIM_LOG_OUT_REPLICATION_STR|SIM_LOG_ENDED_IN_PACKET_STR)</string>
			<key>name</key>
			<string>invalid.illegal.marvell</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match keywords</string>
			<key>match</key>
			<string>(Create new descriptor)</string>
			<key>name</key>
			<string>keyword.marvell</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match keywords</string>
			<key>match</key>
			<string>\b(CMD_FORWARD|CMD_MIRROR|CMD_MIRROR_TO_CPU|CMD_FROM_CPU|CMD_TRAP|CMD_TRAP_TO_CPU|CMD_SOFT_DROP|CMD_HARD_DROP)\b</string>
			<key>name</key>
			<string>entity.name.marvell</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match keywords</string>
			<key>match</key>
			<string>\b(packetCmd)\b</string>
			<key>name</key>
			<string>markup.bold.marvell</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match keywords</string>
			<key>match</key>
			<string>((L3 is .*)|(NO L4 header in this packet)|(ingress packet from SLAN)|(send to SLAN)|(Final packet Hash value))</string>
			<key>name</key>
			<string>support.function.marvell</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match func... and file...</string>
			<key>match</key>
			<string>(FAILED the Router Trigger checks)</string>
			<key>name</key>
			<string>keyword.marvell</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Match func... and file...</string>
			<key>match</key>
			<string>((PASSED the Router Trigger checks)|(No Bridge Bypass))</string>
			<key>name</key>
			<string>entity.name.marvell</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.marvell</string>
	<key>uuid</key>
	<string>0f1542b9-eac7-485c-ade4-2f952adb4de5</string>
</dict>
</plist>
